### ISSUE TITLE
Rotate_prepare is not working

### ISSUE THREAD

**Issue by EJHyun** [Shirley-YFY/SNPM#2]
Hi I have some problems.

Firstly, "[loc-gowalla_totalCheckins.txt.gz](http://snap.stanford.edu/data/loc-gowalla_totalCheckins.txt.gz)" <-- is this file is what you call "checkins-gowalla.txt" ??

Secondly, it seems utils.py in Rotate_prepare is not working.
![image](https://github.com/Shirley-YFY/SNPM/assets/56884260/0cc44066-4b98-4e73-b928-912c8e87d552)

**Comment by EJHyun** [comment]
I found it works with "checkins-gowalla.txt" from repository: Graph-Flashback.

**Comment by Shirley-YFY** [comment]
........
